### ISSUE TITLE
File still being created as thewatchman_report.txt

### ISSUE THREAD

**Issue by kaizersoje** [dummylabs/thewatchman#13]
I have installed v0.4.0. As per the release notes, it said that default report file name was changed to `watchman.txt`. However, the file is still being created as `thewatchman_report.txt`

I noticed in the `const.py` file that the `DEFAULT_REPORT_FILENAME` parameter is `"thewatchman_report.txt"`

**Comment by dummylabs** [comment]
Thanks for the report, this is a bug and will be fixed in the next version. It should only be reproduced when you install 0.4.0 or later using `configuration.yaml` entry with no `report_path` specified. If you install 0.4.0 from scratch without `configuration.yaml` entry, default report value will be `watchman.txt` as advertised.
The workaround is to set desired report path in the integration settings.

**Comment by dummylabs** [comment]
Fixed in v0.5.0
