### ISSUE TITLE
Bad sensor detection

### ISSUE THREAD

**Issue by tapsystem** [dummylabs/thewatchman#143]
Hello,

I've just encounter a big crash with  a backup restauration problem with a lot of lost element and your integration save my life  ... i love you !!!

During this backup and redeployment process i've noted that watchman was making a bad identification of a service and it estimates that as a sensor :  
service input_boolean.turn_on  is identify as missing sensor  >>  input_boolean.turn_ [missing] scripts.yaml:494,553,620

i hope it's can help for futur update :)

**Comment by dummylabs** [comment]
Watchman should correctly identify `input_boolean.turn_on` as a service, tested on 0.6.5. It checks every "entity" candidate to be present within HA service registry before adding it to the report. However, if your config/scripts/automations use a part of id (as `input_boolean.turn_` in the example above) it will be treated as an entity because HA doesn't have such a service.
