### ISSUE TITLE
What is the Execution frequency and can it be modified?

### ISSUE THREAD

**Issue by benquan** [dummylabs/thewatchman#145]
I have been searching for the execution frequency of the report and possibly a modifiable parameter, but could not find it. Is there an option for this?

**Comment by dummylabs** [comment]
Hi @benquan , the new report isn’t generated automatically unless you explicitly invoke the service. By setting up an automation, you can run it at your desired frequency. However, Watchman keeps the state of entities from the previous report in memory and can update them automatically when specific events occur so that the missing entities/services sensor shows the actual numbers:
1. When an entity from the list of previously parsed configuration entities changes its state from unavailable/missing to available or vice versa.
2. When the user reloads the configuration.
3. When Home Assistant starts.
Hope this helps.

**Comment by Adavidebaba** [comment]
> Hi @benquan , the new report isn’t generated automatically unless you explicitly invoke the service. By setting up an automation, you can run it at your desired frequency. However, Watchman keeps the state of entities from the previous report in memory and can update them automatically when specific events occur so that the missing entities/services sensor shows the actual numbers:
> 
> 1. When an entity from the list of previously parsed configuration entities changes its state from unavailable/missing to available or vice versa.
> 2. When the user reloads the configuration.
> 3. When Home Assistant starts.
>    Hope this helps.

Hi Dummylabs, i'm trying to receive a notification whenever a device or a service is missing. I've tried to set up an automation (see sscreenshot) that triggers the creation of the report when the number of devices or services missing changes but it never triggers? Can you help me to make it works? Thanks!!


<img width="1111" alt="Screenshot 2024-10-30 alle 18 23 14" src="https://github.com/user-attachments/assets/805059a0-1206-4099-9fb4-5608bc3d78ab">
