### ISSUE TITLE
Installed last version caused HASS to crash

### ISSUE THREAD

**Issue by malosaa** [dummylabs/thewatchman#38]
Hi,

I did see this plugin on youtube, and i wanted to try it aswell.
Well i downloaded this last version on hacs, and after rebooting hass i went to devices and wanted to add the Watchmen.
After that it starts spinning endless while adding it, causing my home assistant to get unresponsive and i can't connect to it.
So i need to manual reboot the host.

I'm running Home Assistant OS 7.5 on virtualbox, last Homeassistant 2022.4.7

regards

**Comment by malosaa** [comment]
I did tru the version before it, same issue.
keeps doing like this, and home-assistant is not working anymore, can't access it anymore.
The only thing i can do is just restarting the host, as restarting supervisor doesnt do anything.

I did upgrade supervisor this morning, maybe a problem with that ? 

![image](https://user-images.githubusercontent.com/13116501/165285315-5b798b5f-8cde-4225-b37c-83466cc2caa0.png)

**Comment by dummylabs** [comment]
Hey @malosaa, I've just installed 2022.4.7 in my dev environment and tested it, watchman installation works flawlessly. Supervisor should not affect it as well, in theory. It looks weird, frankly, I had no issues like this from watchman users before.  

So far I can only suggest to test if this behaviour somehow related to your configuration. To do this you can:
1. Create new vm with fresh installation of HA, install HACS and watchman, check if its working
2. Make a backup configuration of current instance, restore backup on new vm without custom integrations (only configuration files) and check if watchman is still working.
3. Restore integrations from the backup and check watchman again

Please also make sure that you don't have `watchman:` section in your HA yaml configuration.

By doing this we can check if:
1. Problem was caused by your current HA instance (accumulated errors, etc)
2. Problem was caused by HA configuration files which forced watchman to hang (unlikely, but worth checking)
3. Problem was caused by a custom integration

**Comment by malosaa** [comment]
Hi @dummylabs 

First of all sorry for opening a issue, as i love your add-on!
Yes i did install it on my test system but it was on the last 2022.4.6 not 4.7 and it worked perfect.

So i installed it on my main system and i get endless loading thing..
What i did was i pressed refresh the page, and my home assistant was unreachable ...
I went on my terminal and executed supervisor restart, nothing happens.
And i needed to do a full host restart.

After that i logged in again, and did try the same thing.. still crashing.
So i decided to downgrade the version, that worked but here is the weird part, after 5 minutes the whole system went unavailavle, and this time it fully restarted my system (the VM) and when loaded it put back my backup from last night... 

All the times not even a thing in the logs either..

I still don't understand what happened, as now on the new CORE beta it works normal... not even a crash.

I really don't even know what was going on, but it works now.


So i don't know if it was caused by this add-on but who knows, atleast its working now :) 
Regards and keep the good work up!! love this add-on!
