### ISSUE TITLE
HACS showing false available updates

### ISSUE THREAD

**Issue by satyambaba** [dummylabs/thewatchman#42]
After I upgraded to HA 2022.5, HACS is showing available updates falsely. Please look at this screenshot.

![Screenshot 2022-05-05 052025](https://user-images.githubusercontent.com/6833101/166843054-60bfb51f-e937-4eab-b032-2cf211108122.jpg)

For example - it is showing to update from v0.5.2 to v0.5.1, however v0.5.2 is the latest version which is already installed.

The github also shows the latest release as v0.5.2. https://github.com/dummylabs/thewatchman/releases/

**Comment by satyambaba** [comment]
It is possible that you are facing the same bug as https://github.com/hacs/integration/issues/2556

**Comment by dreimer1986** [comment]
For me it does not show 0.5.2 release anymore. Same one like this: https://github.com/dummylabs/thewatchman/issues/39

**Comment by rubicon** [comment]
If you go to releases on this repo, it shows the latest as 0.5.1. I’m also on 0.5.2 getting the same message up(down)grade message. the 0.5.2 tag can be found under releases but does not show at the top as the latest release. 

I believe issue #43 has it right about the cause being the version tag is set to V.0.5.2 instead of V0.5.2 (not the period after the V.

**Comment by dummylabs** [comment]
This is an intermitted problem on the github side since the middle of March (see the last comment [here](https://github.com/hacs/integration/issues/2556#issuecomment-1079883139)).
There is a workaround for that I use to bring last release back, HACS should work as expected now.
Feel free to reopen this ticket in case the problem happens again.

**Comment by Daneish** [comment]
GitHub Releases for the repo (and HACS) has now reverted back [v0.2.5 2022-02-06](https://github.com/dummylabs/thewatchman/releases/tag/v0.2.5). The workaround might be needed again.

**Comment by dummylabs** [comment]
Thanks, should be fixed now.

**Comment by Daneish** [comment]
Confirmed all good on my side. Thanks very much!
