### ISSUE TITLE
Version naming incorrect 

### ISSUE THREAD

**Issue by stroodle96** [dummylabs/thewatchman#43]
Hello,
I keeps seeing in hacs that I need to "upgrade" from v.0.5.2 to V0.5.1.
I think this is because of the extra period between V and 0 in the V.0.5.2 version.   See the attached image. 

![Screenshot_20220505-103541_Home Assistant](https://user-images.githubusercontent.com/43659890/166947785-2ab0a8c1-fdbf-42c2-90f5-7589e7321d62.jpg)

**Comment by rubicon** [comment]
Same experience here.

**Comment by livlif2dfullest** [comment]
Same issue here as well.  Running HA via docker compose, if that makes any difference.

**Comment by dummylabs** [comment]
Hey @stroodle96, version tag scheme (extra period) has nothing to do with this issue, this is a problem on the github side since the middle of March (see the last comment [here](https://github.com/hacs/integration/issues/2556#issuecomment-1079883139)). 
There is a workaround for that I use to bring last release back, HACS should work as expected now. 
Feel free to reopen this ticket in case the problem happens again.
