### ISSUE TITLE
versioning is wrong?

### ISSUE THREAD

**Issue by joostvkempen** [dummylabs/thewatchman#46]
In HACS there's a new version announced, only it's a downgrade?

![image](https://user-images.githubusercontent.com/37901988/167645921-f45d1048-2288-4a6c-9ae5-8cd4740524f7.png)

On Github only releases till 2.5.0 are shown? Something wrong?

**Comment by dreimer1986** [comment]
https://github.com/dummylabs/thewatchman/issues/43
https://github.com/dummylabs/thewatchman/issues/42
https://github.com/dummylabs/thewatchman/issues/39
GitHub loves @dummylabs

**Comment by pejotigrek** [comment]
sorry for hooking up to closed issue, but seems like it is active still :(

![image](https://user-images.githubusercontent.com/10796588/168015376-0747d27a-0034-47ef-af19-42aca680ae02.png)

**Comment by dummylabs** [comment]
Hey @pejotigrek, no probs. I've opened a ticket on github for this problem, it seems they did something because yesterday only 0.5.2 was available on [release page](https://github.com/dummylabs/thewatchman/releases), now all previous releases are shown as well. May be this is the reason why 0.5.1 became "most recent". 
I've applied recommended workaround again (hopefully, for the last time 😀), please update information in HACS (three dots menu next to Watchman entry in HACS).

**Comment by pejotigrek** [comment]
thanks @dummylabs! information update did the trick :)
